/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.EstoqueDAO;
import Dao.ProdutoDAO;
import Model.Estoque;
import Model.Produtos;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Heitor Lopes
 */
public class TIAdicionarEstoque extends javax.swing.JFrame {

    /**
     * Creates new form TIAdicionarProduto
     */
    public TIAdicionarEstoque() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        codigo = new javax.swing.JFormattedTextField();
        loja = new javax.swing.JFormattedTextField();
        bot = new javax.swing.JPanel();
        adicionarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(118, 180, 247));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        top.setBackground(new java.awt.Color(118, 180, 247));
        top.setLayout(new java.awt.GridLayout(1, 0));

        codigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        codigo.setPreferredSize(new java.awt.Dimension(110, 40));
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        top.add(codigo);

        loja.setBorder(javax.swing.BorderFactory.createTitledBorder("Loja"));
        loja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lojaActionPerformed(evt);
            }
        });
        top.add(loja);

        jPanel1.add(top);

        bot.setBackground(new java.awt.Color(118, 180, 247));
        bot.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 80, 5));

        adicionarBtn.setText("Adicionar");
        adicionarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        adicionarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarBtnActionPerformed(evt);
            }
        });
        bot.add(adicionarBtn);

        cancelarBtn.setText("Cancelar");
        cancelarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        bot.add(cancelarBtn);

        jPanel1.add(bot);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void lojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lojaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lojaActionPerformed

    private void adicionarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarBtnActionPerformed
        try{
        int c = Integer.parseInt(codigo.getText());
        String d = loja.getText();

        Estoque estoque = new Estoque(c, d);

        EstoqueDAO estoqueDAO = new EstoqueDAO();

        estoqueDAO.inserir(estoque);
        TIEscolhaEstoque.atualizarTabela();
        setVisible(false);
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Ocorreu um erro. Verifique se os campos foram digitados corretamente.");
        }
        
    }//GEN-LAST:event_adicionarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIAdicionarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIAdicionarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIAdicionarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIAdicionarEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIAdicionarEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarBtn;
    private javax.swing.JPanel bot;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JFormattedTextField codigo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField loja;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
