/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.ProdutoDAO;
import Model.Produtos;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Heitor Lopes
 */
public class TIAdicionarFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form TIAdicionarProduto
     */
    public TIAdicionarFornecedor() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        codigo = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        bot = new javax.swing.JPanel();
        adicionarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(118, 180, 247));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        top.setBackground(new java.awt.Color(118, 180, 247));
        top.setLayout(new java.awt.GridLayout(1, 6));

        jPanel3.setBackground(new java.awt.Color(118, 180, 247));

        codigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        codigo.setPreferredSize(new java.awt.Dimension(110, 40));
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        jPanel3.add(codigo);

        top.add(jPanel3);

        jPanel7.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Fornecedor");
        jPanel7.add(jLabel1);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(jComboBox3);

        top.add(jPanel7);

        jPanel6.setLayout(new java.awt.GridLayout(2, 0));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Estoque");
        jPanel6.add(jLabel2);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(jComboBox4);

        top.add(jPanel6);

        jPanel1.add(top);

        bot.setBackground(new java.awt.Color(118, 180, 247));
        bot.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 80, 5));

        adicionarBtn.setText("Adicionar");
        adicionarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        adicionarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarBtnActionPerformed(evt);
            }
        });
        bot.add(adicionarBtn);

        cancelarBtn.setText("Cancelar");
        cancelarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        bot.add(cancelarBtn);

        jPanel1.add(bot);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void adicionarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarBtnActionPerformed
        try{
        int c = Integer.parseInt(codigo.getText());
        String d = descricao.getText();
        int q = Integer.parseInt(quantidade.getText());
        double p = Double.parseDouble(preco.getText());
        String f = fornecedor.getText();
        int e = Integer.parseInt(estoque.getText());
        
        Produtos produto = new Produtos(c, d, q, p, f, e);
        
        ProdutoDAO produtoDAO = new ProdutoDAO();
        
        produtoDAO.inserir(produto);
        
        setVisible(false);
        TICompras.atualizarTabela();
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Ocorreu um erro. Verifique se os campos foram digitados corretamente.");
        }
    }//GEN-LAST:event_adicionarBtnActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIAdicionarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIAdicionarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIAdicionarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIAdicionarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIAdicionarFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarBtn;
    private javax.swing.JPanel bot;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JFormattedTextField codigo;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
