/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.EstoqueDAO;
import Model.Estoque;
import Utils.codigoProdutoEstoque;
import javax.swing.JOptionPane;

/**
 *
 * @author Heitor Lopes
 */
public class TIEscolhaEstoque extends javax.swing.JFrame {

    /**
     * Creates new form TIEstoque
     */
    public TIEscolhaEstoque() {
        initComponents();
        setLocationRelativeTo(null);
        atualizarTabela();
        
    }
    
    public static void atualizarTabela() {
        
        tabelaEstoque.removeAll();
        
        EstoqueDAO estoqueDAO = new EstoqueDAO();
        
        int cont = 0;
        for (Estoque estoque : estoqueDAO.listar()) {
            tabelaEstoque.setValueAt(estoque.getCodigo(), cont, 0);
            tabelaEstoque.setValueAt(estoque.getLoja(), cont, 1);
            cont++;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top = new javax.swing.JPanel();
        conteudo = new javax.swing.JPanel();
        estoqueLabel = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        mid = new javax.swing.JPanel();
        midTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        midBot = new javax.swing.JPanel();
        adicionarBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        excluirBtn = new javax.swing.JButton();
        bot = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEstoque = new javax.swing.JTable();
        estoqueBtn = new javax.swing.JButton();
        voltarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 450));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        top.setBackground(new java.awt.Color(118, 180, 247));
        top.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        conteudo.setBackground(new java.awt.Color(118, 180, 247));
        conteudo.setLayout(new java.awt.GridLayout(2, 0));

        estoqueLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Estoque.png"))); // NOI18N
        conteudo.add(estoqueLabel);

        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Escolha uma loja");
        titulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        conteudo.add(titulo);

        top.add(conteudo);

        getContentPane().add(top);

        mid.setBackground(new java.awt.Color(118, 180, 247));
        mid.setLayout(new java.awt.GridLayout(2, 0));

        midTop.setBackground(new java.awt.Color(118, 180, 247));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 40);
        flowLayout1.setAlignOnBaseline(true);
        midTop.setLayout(flowLayout1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Sem título.png"))); // NOI18N
        midTop.add(jLabel1);

        jTextField1.setPreferredSize(new java.awt.Dimension(200, 30));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        midTop.add(jTextField1);

        mid.add(midTop);

        midBot.setBackground(new java.awt.Color(118, 180, 247));
        midBot.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 20));

        adicionarBtn.setText("Adicionar");
        adicionarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        adicionarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarBtnActionPerformed(evt);
            }
        });
        midBot.add(adicionarBtn);

        modificarBtn.setText("Modificar");
        modificarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });
        midBot.add(modificarBtn);

        excluirBtn.setText("Excluir");
        excluirBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        excluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBtnActionPerformed(evt);
            }
        });
        midBot.add(excluirBtn);

        mid.add(midBot);

        getContentPane().add(mid);

        bot.setBackground(new java.awt.Color(118, 180, 247));
        bot.setLayout(new java.awt.BorderLayout());

        tabelaEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código", "Loja"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaEstoque);

        bot.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        estoqueBtn.setText("Estoque");
        estoqueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueBtnActionPerformed(evt);
            }
        });
        bot.add(estoqueBtn, java.awt.BorderLayout.LINE_END);

        voltarBtn.setText("Voltar");
        voltarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });
        bot.add(voltarBtn, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(bot);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void adicionarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarBtnActionPerformed
        new TIAdicionarEstoque().setVisible(true);
    }//GEN-LAST:event_adicionarBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        new TIModificarEstoque1().setVisible(true);
    }//GEN-LAST:event_modificarBtnActionPerformed

    private void excluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBtnActionPerformed
        setVisible(false);
        new TIExcluirEstoque().setVisible(true);
    }//GEN-LAST:event_excluirBtnActionPerformed

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        setVisible(false);
        new TIInicio().setVisible(true);
    }//GEN-LAST:event_voltarBtnActionPerformed

    private void estoqueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueBtnActionPerformed
        try{
        int c = Integer.parseInt(JOptionPane.showInputDialog(null, "Qual estoque você deseja acessar?"));
        
        EstoqueDAO estoqueDAO = new EstoqueDAO();
        
        if (estoqueDAO.existsEstoque(c)) {
            codigoProdutoEstoque.codigoProduto = c;
            setVisible(false);
            new TIEstoque().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "O estoque não existe.");
        }
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Ocorreu um erro. Verifique se os campos foram digitados corretamente.");
        }

    }//GEN-LAST:event_estoqueBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIEscolhaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIEscolhaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIEscolhaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIEscolhaEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIEscolhaEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarBtn;
    private javax.swing.JPanel bot;
    private javax.swing.JPanel conteudo;
    private javax.swing.JButton estoqueBtn;
    private javax.swing.JLabel estoqueLabel;
    private javax.swing.JButton excluirBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mid;
    private javax.swing.JPanel midBot;
    private javax.swing.JPanel midTop;
    private javax.swing.JButton modificarBtn;
    private static javax.swing.JTable tabelaEstoque;
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel top;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
