/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.ProdutoDAO;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Heitor Lopes
 */
public class TIExcluirProduto_Vendas extends javax.swing.JFrame {

    /**
     * Creates new form TIExcluirProduto_Compras
     */
    public TIExcluirProduto_Vendas() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bot = new javax.swing.JPanel();
        cancelarBtn = new javax.swing.JButton();
        excluirBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(2, 0));

        top.setBackground(new java.awt.Color(118, 180, 247));
        top.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Deseja realmente excluir?");
        top.add(jLabel1);

        getContentPane().add(top);

        bot.setBackground(new java.awt.Color(118, 180, 247));
        bot.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 80, 5));

        cancelarBtn.setText("Cancelar");
        cancelarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        bot.add(cancelarBtn);

        excluirBtn.setText("Excluir");
        excluirBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        excluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBtnActionPerformed(evt);
            }
        });
        bot.add(excluirBtn);

        getContentPane().add(bot);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBtnActionPerformed
        try{
        int c = Integer.parseInt(codigo.getText());

        ProdutoDAO produtoDAO = new ProdutoDAO();
        produtoDAO.excluir(c);

        setVisible(false);
        TIVendas n = new TIVendas();
        n.setVisible(true);
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Ocorreu um erro. Verifique se os campos foram digitados corretamente.");
        }
    }//GEN-LAST:event_excluirBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIExcluirProduto_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIExcluirProduto_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIExcluirProduto_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIExcluirProduto_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIExcluirProduto_Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bot;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JButton excluirBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
