/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.ProdutoDAO;
import Model.Produtos;
import java.util.ArrayList;

/**
 *
 * @author Heitor Lopes
 */
public class TIFornecedor extends javax.swing.JFrame {
    
    ArrayList<Produtos> produtos = new ArrayList<>();

   
    public static void atualizarTabela() {
        
        tabelaCompras.removeAll();
        
        ProdutoDAO produtoDAO = new ProdutoDAO();
        
        int cont = 0;
        for (Produtos produto : produtoDAO.listar()) {
            tabelaCompras.setValueAt(produto.getCodigo(), cont, 0);
            tabelaCompras.setValueAt(produto.getDescricao(), cont, 1);
            tabelaCompras.setValueAt(produto.getQuantidade(), cont, 2);
            tabelaCompras.setValueAt(produto.getPreco(), cont, 3);
            tabelaCompras.setValueAt(produto.getFornecedor(), cont, 4);
            tabelaCompras.setValueAt(produto.getEstoque(), cont, 5);
            cont++;
        }
        
    }
    
    public TIFornecedor() {
        initComponents();
        atualizarTabela();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top = new javax.swing.JPanel();
        mid = new javax.swing.JPanel();
        midTop = new javax.swing.JPanel();
        pesquisarLabel = new javax.swing.JLabel();
        pesquisar = new javax.swing.JTextField();
        midBot = new javax.swing.JPanel();
        adicionarBtn = new javax.swing.JButton();
        modificarBtn = new javax.swing.JButton();
        excluirBtn = new javax.swing.JButton();
        voltarBtn = new javax.swing.JButton();
        bot = new javax.swing.JPanel();
        scrollForTable = new javax.swing.JScrollPane();
        tabelaCompras = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(326, 10));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        top.setBackground(new java.awt.Color(118, 180, 247));
        top.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));
        getContentPane().add(top);

        mid.setBackground(new java.awt.Color(118, 180, 247));
        mid.setLayout(new java.awt.GridLayout(2, 0));

        midTop.setBackground(new java.awt.Color(118, 180, 247));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 40);
        flowLayout2.setAlignOnBaseline(true);
        midTop.setLayout(flowLayout2);

        pesquisarLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/Sem título.png"))); // NOI18N
        midTop.add(pesquisarLabel);

        pesquisar.setPreferredSize(new java.awt.Dimension(200, 30));
        midTop.add(pesquisar);

        mid.add(midTop);

        midBot.setBackground(new java.awt.Color(118, 180, 247));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 20);
        flowLayout1.setAlignOnBaseline(true);
        midBot.setLayout(flowLayout1);

        adicionarBtn.setText("Adicionar");
        adicionarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        adicionarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarBtnActionPerformed(evt);
            }
        });
        midBot.add(adicionarBtn);

        modificarBtn.setText("Modificar");
        modificarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        modificarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBtnActionPerformed(evt);
            }
        });
        midBot.add(modificarBtn);

        excluirBtn.setText("Excluir");
        excluirBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        excluirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirBtnActionPerformed(evt);
            }
        });
        midBot.add(excluirBtn);

        voltarBtn.setText("Voltar");
        voltarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });
        midBot.add(voltarBtn);

        mid.add(midBot);

        getContentPane().add(mid);

        bot.setBackground(new java.awt.Color(118, 180, 247));
        bot.setLayout(new java.awt.GridLayout(1, 0));

        tabelaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CPF", "Nome", "Cidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelaCompras.setEnabled(false);
        scrollForTable.setViewportView(tabelaCompras);

        bot.add(scrollForTable);

        getContentPane().add(bot);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adicionarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarBtnActionPerformed
        
        TIAdicionarProduto_Compras adicionarProduto = new TIAdicionarProduto_Compras();
        
        adicionarProduto.setVisible(true);

    }//GEN-LAST:event_adicionarBtnActionPerformed

    private void excluirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirBtnActionPerformed
        TIExcluirProduto_Compras excluir = new TIExcluirProduto_Compras();
        setVisible(false);
        excluir.setVisible(true);

    }//GEN-LAST:event_excluirBtnActionPerformed

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        
        TIInicio inicio = new TIInicio();
        
        setVisible(false);
        inicio.setVisible(true);

    }//GEN-LAST:event_voltarBtnActionPerformed

    private void modificarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBtnActionPerformed
        TIModificarProduto_Compras modificarProduto = new TIModificarProduto_Compras();
        
        modificarProduto.setVisible(true);
    }//GEN-LAST:event_modificarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarBtn;
    private javax.swing.JPanel bot;
    private javax.swing.JButton excluirBtn;
    private javax.swing.JPanel mid;
    private javax.swing.JPanel midBot;
    private javax.swing.JPanel midTop;
    private javax.swing.JButton modificarBtn;
    private javax.swing.JTextField pesquisar;
    private javax.swing.JLabel pesquisarLabel;
    private javax.swing.JScrollPane scrollForTable;
    private static javax.swing.JTable tabelaCompras;
    private javax.swing.JPanel top;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
