/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Heitor Lopes
 */
public class TIInicio extends javax.swing.JFrame {

    /**
     * Creates new form EstoqueControle
     */
    public TIInicio() {
        initComponents();
        setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        top = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        mid = new javax.swing.JPanel();
        midTop = new javax.swing.JPanel();
        comprasBtn = new javax.swing.JButton();
        midMid = new javax.swing.JPanel();
        vendasBtn = new javax.swing.JButton();
        midBot = new javax.swing.JPanel();
        escolhaEstoqueBtn = new javax.swing.JButton();
        bot = new javax.swing.JPanel();
        sairBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(118, 180, 247));
        setMaximumSize(new java.awt.Dimension(400, 402));
        setMinimumSize(new java.awt.Dimension(400, 402));
        getContentPane().setLayout(new java.awt.GridLayout(3, 1));

        top.setBackground(new java.awt.Color(118, 180, 247));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30);
        flowLayout1.setAlignOnBaseline(true);
        top.setLayout(flowLayout1);
        top.add(logo);

        getContentPane().add(top);

        mid.setBackground(new java.awt.Color(118, 180, 247));
        mid.setLayout(new java.awt.GridLayout(3, 0));

        midTop.setBackground(new java.awt.Color(118, 180, 247));
        midTop.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        comprasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/grey_new_seo2-35-512.png"))); // NOI18N
        comprasBtn.setText("Compras");
        comprasBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        comprasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprasBtnActionPerformed(evt);
            }
        });
        midTop.add(comprasBtn);

        mid.add(midTop);

        midMid.setBackground(new java.awt.Color(118, 180, 247));
        midMid.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        vendasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/e2-512.png"))); // NOI18N
        vendasBtn.setText("Vendas");
        vendasBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        vendasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendasBtnActionPerformed(evt);
            }
        });
        midMid.add(vendasBtn);

        mid.add(midMid);

        midBot.setBackground(new java.awt.Color(118, 180, 247));
        midBot.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 15));

        escolhaEstoqueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/stock_control.png"))); // NOI18N
        escolhaEstoqueBtn.setText("Escolha de Estoque");
        escolhaEstoqueBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        escolhaEstoqueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escolhaEstoqueBtnActionPerformed(evt);
            }
        });
        midBot.add(escolhaEstoqueBtn);

        mid.add(midBot);

        getContentPane().add(mid);

        bot.setBackground(new java.awt.Color(118, 180, 247));
        bot.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 30));

        sairBtn.setText("Sair");
        sairBtn.setPreferredSize(new java.awt.Dimension(170, 40));
        sairBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairBtnActionPerformed(evt);
            }
        });
        bot.add(sairBtn);

        getContentPane().add(bot);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprasBtnActionPerformed

        TICompras compras = new TICompras();
        
        setVisible(false);
        compras.setVisible(true);

    }//GEN-LAST:event_comprasBtnActionPerformed

    private void escolhaEstoqueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escolhaEstoqueBtnActionPerformed
        setVisible(false);
        new TIEscolhaEstoque().setVisible(true);

    }//GEN-LAST:event_escolhaEstoqueBtnActionPerformed

    private void sairBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairBtnActionPerformed
        System.exit(0);        
    }//GEN-LAST:event_sairBtnActionPerformed

    private void vendasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendasBtnActionPerformed
        TIVendas vendas = new TIVendas();
        setVisible(false);
        vendas.setVisible(true);

    }//GEN-LAST:event_vendasBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bot;
    private javax.swing.JButton comprasBtn;
    private javax.swing.JButton escolhaEstoqueBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel mid;
    private javax.swing.JPanel midBot;
    private javax.swing.JPanel midMid;
    private javax.swing.JPanel midTop;
    private javax.swing.JButton sairBtn;
    private javax.swing.JPanel top;
    private javax.swing.JButton vendasBtn;
    // End of variables declaration//GEN-END:variables
}
