/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Dao.ProdutoDAO;
import Model.Produtos;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author Heitor Lopes
 */
public class TIModificarProduto_Vendas extends javax.swing.JFrame {

    /**
     * Creates new form TIAdicionarProduto
     */
    public TIModificarProduto_Vendas() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        codigo = new javax.swing.JFormattedTextField();
        descricao = new javax.swing.JFormattedTextField();
        quantidade = new javax.swing.JFormattedTextField();
        preco = new javax.swing.JFormattedTextField();
        fornecedor = new javax.swing.JFormattedTextField();
        estoque = new javax.swing.JFormattedTextField();
        bot = new javax.swing.JPanel();
        adicionarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(118, 180, 247));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        top.setBackground(new java.awt.Color(118, 180, 247));
        top.setLayout(new java.awt.GridLayout(1, 0));

        codigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Código"));
        codigo.setPreferredSize(new java.awt.Dimension(110, 40));
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        top.add(codigo);

        descricao.setBorder(javax.swing.BorderFactory.createTitledBorder("Descrição"));
        descricao.setPreferredSize(new java.awt.Dimension(110, 40));
        descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descricaoActionPerformed(evt);
            }
        });
        top.add(descricao);

        quantidade.setBorder(javax.swing.BorderFactory.createTitledBorder("Quantidade"));
        quantidade.setPreferredSize(new java.awt.Dimension(110, 40));
        quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeActionPerformed(evt);
            }
        });
        top.add(quantidade);

        preco.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Preço")));
        preco.setPreferredSize(new java.awt.Dimension(110, 40));
        top.add(preco);

        fornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Fornecedor"));
        fornecedor.setPreferredSize(new java.awt.Dimension(110, 40));
        top.add(fornecedor);

        estoque.setBorder(javax.swing.BorderFactory.createTitledBorder("Estoque"));
        estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estoqueActionPerformed(evt);
            }
        });
        top.add(estoque);

        jPanel1.add(top);

        bot.setBackground(new java.awt.Color(118, 180, 247));
        bot.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 80, 5));

        adicionarBtn.setText("Modificar");
        adicionarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        adicionarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarBtnActionPerformed(evt);
            }
        });
        bot.add(adicionarBtn);

        cancelarBtn.setText("Cancelar");
        cancelarBtn.setPreferredSize(new java.awt.Dimension(110, 40));
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });
        bot.add(cancelarBtn);

        jPanel1.add(bot);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descricaoActionPerformed

    private void quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantidadeActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelarBtnActionPerformed

    private void adicionarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarBtnActionPerformed
        try{
        int c = Integer.parseInt(codigo.getText());
        String d = descricao.getText();
        int q = Integer.parseInt(quantidade.getText());
        double p = Double.parseDouble(preco.getText());
        String f = fornecedor.getText();
        int e = Integer.parseInt(estoque.getText());

        Produtos produto = new Produtos(c, d, q, p, f, e);

        ProdutoDAO produtoDAO = new ProdutoDAO();

        produtoDAO.alterar(produto);

        setVisible(false);
        TIVendas.atualizarTabela();
        }catch(NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Ocorreu um erro. Verifique se os campos foram digitados corretamente.");
        }
    }//GEN-LAST:event_adicionarBtnActionPerformed

    private void estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TIModificarProduto_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TIModificarProduto_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TIModificarProduto_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TIModificarProduto_Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TIModificarProduto_Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarBtn;
    private javax.swing.JPanel bot;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JFormattedTextField codigo;
    private javax.swing.JFormattedTextField descricao;
    private javax.swing.JFormattedTextField estoque;
    private javax.swing.JFormattedTextField fornecedor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField preco;
    private javax.swing.JFormattedTextField quantidade;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
